### ISSUE TITLE
remove bower

### ISSUE THREAD

**Issue by dancinglightning** [blocknotes/rails-vue-example#1]
Hi,
landed here from googling rails and vue (so i guess others will too).
Still figuring out how to best integrate vue; i would like to avoid js build tools and webpacker for now.

There is a an asset gem that packages vue https://github.com/adambutler/vuejs-rails
I have integrated that into your example app and would be happy to make a pull request, if you'd accept. That removes bower, i would change the readme accordingly

Torsten

**Comment by blocknotes** [comment]
Hi Torsten, thank you for your message.
To be honest this project is outdated :)
It was a first experiment to use Vue with Rails.
Actually with Rails 5.1 I would point on webpack or webpacker ...

**Comment by dancinglightning** [comment]
Hi Mattia,
i use rails 5.1 too. And maybe i wasn't clear, i offered the update, so other people who land here would see it.

I played with webpacker, and it seems slightly raw, unfinished. And anyway, it introduces a development and production dependencies that i'd rather not have. Webpacker or was it yarn needs, not just any Node, but the latest, and on a slightly older system, that is a pain to install.

Since vue is just a singe js file (like jquery) i think the asset approach works well, and i would document that. Even the cdn is better than the bower, as that does not work anymore.

**Comment by blocknotes** [comment]
I think the same about webpacker.
Yarn requirements... are you sure about latest Node only?
On their website they say: ^4.8.0 || ^5.7.0 || ^6.2.2 || ^8.0.0

By the way, you are free to do anything of course - a fork by yourserlf, a new project, a different branch here (something like rails51 for example) - the same for me.

To be honest I'm a back-end only developer from some months, some of my front-end workmates use different way to connect Rails with Vue / React - they would fit better for this task.

**Comment by dancinglightning** [comment]
Maybe it's "just" node 8, but nothing you can install standard way 
(apt-get) on my debian box.
I know i can fork, but since google points to your repository that 
doesn't help anyone.

I am not asking work of you, if that's what you think. The only thing 
is, if i make a pull, will you press the button?

**Comment by blocknotes** [comment]
I'm a Debian fan :P usually it's good, but yes, often the problems are caused by outdated packages.

Sure, it's not a problem to accept a good PR :)
It's good if someone wants to contribute in one of my repos.

Ok, let's do in this way: I make a rails4 branch to leave the old version just for reference with a link in the README
